#!/usr/bin/env bash

get_brightness() {
    echo $(brightnessctl -m | cut -d, -f4)
}

notify_user() {
    notify-send -h string:x-canonical-private-synchronous:sys-notify \
        -c "overlay" "Brightness: $(get_brightness)"
}

# Execute accordingly
case "$1" in
"--inc")
    brightnessctl -c backlight set +5% && notify_user
    ;;
"--dec")
    brightnessctl -c backlight set 5%- && notify_user
    ;;
esac
