#!/usr/bin/env bash

notify_user() {
    notify-send -h string:x-canonical-private-synchronous:sys-notify \
        -c "overlay" "Layout: $1"
}

change_layout() {
    hyprctl switchxkblayout g915-tkl-keyboard "$1"
    hyprctl switchxkblayout at-translated-set-2-keyboard "$1"
}

# Execute accordingly
case "$1" in
"--us")
    change_layout 0 && notify_user "US"
    ;;
"--ca")
    change_layout 1 && notify_user "CA"
    ;;
esac
