#!/usr/bin/env sh

scripts=$HOME/.config/river/scripts

swww init &
$scripts/swww_random "$HOME/Pictures/Wallpapers" &

# Notification daemon
mako &

# NetworkManager systray applet
nm-applet --indicator &

# Bluetooth systray applet
blueman-applet &

# Start media keys manager
playerctld daemon &

# Starting the clipboard manager
wl-paste --watch cliphist store &

# Starting signal
signal-desktop --start-in-tray &

# Starting spotify_player in daemon mode
spotify_player -d &
